# Generated by Django 5.1.3 on 2024-12-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneWayBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('from_location', models.CharField(max_length=200)),
                ('to_location', models.CharField(max_length=200)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('number_of_seats', models.PositiveIntegerField()),
            ],
        ),
    ]
